In [1]:
import pandas as pd
import numpy as np

In [2]:
diabetes = pd.read_csv('diabetes_prediction_dataset.csv')
diabetes.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [28]:
diabetes["diabetes"].dtype

dtype('int64')

In [3]:
diabetes.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='str')

In [4]:
diabetes.shape

(100000, 9)

In [8]:
diabetes.isna().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [25]:
Outcome=diabetes[diabetes["diabetes"]==1]
Outcome

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
6,Female,44.0,0,0,never,19.31,6.5,200,1
26,Male,67.0,0,1,not current,27.32,6.5,200,1
38,Male,50.0,1,0,current,27.32,5.7,260,1
40,Male,73.0,0,0,former,25.91,9.0,160,1
53,Female,53.0,0,0,former,27.32,7.0,159,1
...,...,...,...,...,...,...,...,...,...
99935,Female,65.0,1,1,never,33.55,8.2,140,1
99938,Male,55.0,0,1,former,30.42,6.2,300,1
99957,Female,61.0,0,0,No Info,34.45,6.5,280,1
99962,Female,58.0,1,0,never,38.31,7.0,200,1
99979,Female,61.0,0,0,current,30.11,6.2,240,1

In [15]:
np.mean(diabetes["blood_glucose_level"])

np.float64(138.05806)

In [21]:
np.max(diabetes["bmi"])

np.float64(95.69)

In [37]:
diabetic_pateints = (diabetes["diabetes"].sum() / len(diabetes))*100
round(diabetic_pateints,2)

np.float64(8.5)

In [39]:
non_diabetic = diabetes[diabetes["diabetes"] == 0]
round(np.mean(non_diabetic["age"]),2)

np.float64(40.12)

In [66]:
Gender = diabetes[(diabetes["blood_glucose_level"]) == (diabetes["blood_glucose_level"]).max()]["gender"]
np.max(Gender)

'Male'

In [57]:
diabetes[diabetes["hypertension"] == 1].count()["hypertension"]

np.int64(7485)

In [49]:
diabetis_pateints = diabetes[diabetes["diabetes"] == 1]
round(np.mean(diabetis_pateints["HbA1c_level"]),2)

np.float64(6.93)

In [58]:
diabetes[diabetes["age"]>40].count()["age"]

np.int64(53128)

In [62]:
diabetes[(diabetes["bmi"]>30) & (diabetes["diabetes"]==1)].count()[["bmi","diabetes"]]

bmi         4232
diabetes    4232
dtype: int64