In [35]:
import pandas as pd
import numpy as np

In [36]:
heart = pd.read_csv("heart.csv")
heart

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [37]:
heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [38]:
null_value = heart.isna().value_counts()
null_value

age    sex    cp     trestbps  chol   fbs    restecg  thalach  exang  oldpeak  slope  ca     thal   target
False  False  False  False     False  False  False    False    False  False    False  False  False  False     1025
Name: count, dtype: int64

In [40]:
null_value.sum()

np.int64(1025)

In [41]:
heart_patient = heart[heart["target"] == 1].value_counts()
heart_patient

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
38   1    2   138       175   0    1        173      0      0.0      2      4   2     1         8
71   0    0   112       149   0    1        125      0      1.6      1      0   2     1         4
58   1    2   140       211   1    0        165      0      0.0      2      0   2     1         4
54   1    2   120       258   0    0        147      0      0.4      1      0   3     1         4
55   0    1   132       342   0    1        166      0      1.2      2      0   2     1         4
                                                                                               ..
              135       250   0    0        161      0      1.4      1      0   2     1         3
60   0    2   120       178   1    1        96       0      0.0      2      0   2     1         3
52   1    0   108       233   1    1        147      0      0.1      2      3   3     1         3
68   0    2   120       211   0    0        115      0      1.5      1      0   2     1         3
44   0    2   108       141   0    1        175      0      0.6      1      0   2     1         3
Name: count, Length: 164, dtype: int64

In [43]:
heart_patient.sum()

np.int64(526)

In [44]:
average_age = heart[heart["target"] == 1].mean()["age"]
round(average_age,2)

np.float64(52.41)

In [45]:
np.max(heart["chol"])

np.int64(564)

In [46]:
age_50 = heart[(heart["target"] == 1) & (heart["age"] >= 50)]
age_50

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
10,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
16,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
18,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
19,58,1,2,140,211,1,0,165,0,0.0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
1006,58,1,2,140,211,1,0,165,0,0.0,2,0,2,1
1007,56,1,3,120,193,0,0,162,0,1.9,1,0,3,1
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1

In [47]:
heart_patient = heart[heart["target"] == 1]
round(np.mean(heart_patient["chol"]),3)

np.float64(240.979)

In [48]:
average_patient = heart_patient.sum()/len(heart) * 100
round(average_patient["target"],3)

np.float64(51.317)

In [50]:
np.min(heart_patient["age"])

np.int64(29)

In [33]:
sex = heart["sex"].value_counts()
sex

sex
1    713
0    312
Name: count, dtype: int64